language: node_js

node_js:
  - '10'

branch:
  only:
    - master

install: npm install

cache:
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: Run Tests
      node_js: '10'
      script:
        - npm test
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage