language: node_js

node_js:
  - '10'

branch:
  only:
    - master


install: npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm run test

deploy:
  provider: npm
  email: "$EMAIL"
  api_key:
    secure: "$NPM_API_KEY"
  on:
    tags: true
    repo: snipey/popular-quotes