language: node_js

node_js:
  - '10'

branch:
  only:
    - master


install: npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm test -- -u

jobs:
  include:
    - stage: npm release
      node_js: '10'
      script: echo "Deploying to npm ..."
      deploy:
        email: contact@snipey.dev
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release